FROM node:14

# Copy the files to the container
WORKDIR /build
COPY . .

# Install deps
RUN yarn install

# This container is just for development and has nothing to actually run, so in order to do that we have to run this hacky command
CMD ["tail", "-F", "anything"]
