name: Feature or Release Branch
on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'release/**'
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js 14.x (LTS)
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn install
      # TODO: Add Step for TypeScript Build
      # TODO: Add Step for Linting
      # TODO: Add Step for Unit Testing
