name: Feature or Release Branch
env:
  NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
on:
  push:
    branches:
      - 'hotfix/**'
      - 'feature/**'
      - 'release/**'
  pull_request:
    branches:
      - 'hotfix/**'
      - 'feature/**'
      - 'release/**'
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js 14.x (LTS)
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
